CREATE DATABASE db_ifoot;
USE db_ifoot;


CREATE TABLE IMAGEM(
	ID_IMAGEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PATH VARCHAR(255) NOT NULL
);


CREATE TABLE PROPRIETARIOS(
	ID_PROP int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_PROP varchar(255) NOT NULL,
	EMAIL_PROP varchar(50) NOT NULL UNIQUE,
	CPF_PROP varchar(11) NOT NULL UNIQUE,
	TEL_PROP varchar(11) NOT NULL,
	SENHA_PROP varchar(255) NOT NULL,
	ID_IMAGEM INT,

	FOREIGN KEY (ID_IMAGEM) REFERENCES IMAGEM(ID_IMAGEM) ON DELETE SET NULL
);

CREATE TABLE MODALIDADES (
	ID_MODAL int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_MODAL varchar(50),
    QTD_MAX_JOG INT NOT NULL
);

CREATE TABLE UF (
	ID_UF int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SIGLA_UF varchar(2) NOT NULL,
	NOME_UF varchar(50) NOT NULL
);

CREATE TABLE QUADRAS (
	ID_QUAD int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PRECO_HORA_QUAD decimal(8,2) NOT NULL,
	ENDERECO_QUAD varchar(255) NOT NULL,
	CIDADE_QUAD varchar(50) NOT NULL,
	ID_PROP int(11) NOT NULL,
	ID_UF int(11) NOT NULL,
	ID_MODAL int(11) NOT NULL,
	STATUS_QUAD tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 = Ativa, 0 = Inativa',
	ID_IMAGEM INT,
    
    FOREIGN KEY (ID_PROP) REFERENCES PROPRIETARIOS (ID_PROP),
    FOREIGN KEY (ID_UF) REFERENCES UF (ID_UF),
    FOREIGN KEY (ID_MODAL) REFERENCES MODALIDADES (ID_MODAL),
	FOREIGN KEY (ID_IMAGEM) REFERENCES IMAGEM(ID_IMAGEM) ON DELETE SET NULL
);

CREATE TABLE JOGADORES (
	ID_JOG int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_JOG varchar(255) NOT NULL,
	EMAIL_JOG varchar(50) NOT NULL UNIQUE,
	CPF_JOG varchar(11) NOT NULL UNIQUE,
	CIDADE_JOG varchar(50) NOT NULL,
	ENDERECO_JOG varchar(255) NOT NULL,
	TEL_JOG varchar(11) NOT NULL,
	SENHA_JOG varchar(255) NOT NULL,
	ID_UF int(11) NOT NULL,
	ID_IMAGEM INT,
    
    FOREIGN KEY (ID_UF) REFERENCES UF (ID_UF),
	FOREIGN KEY (ID_IMAGEM) REFERENCES IMAGEM(ID_IMAGEM) ON DELETE SET NULL
);

CREATE TABLE PARTIDAS (
	ID_PTD int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA_PTD date NOT NULL,
	HORARIO_INICIO_PTD time NOT NULL,
	HORARIO_FIM_PTD time NOT NULL,
    PRECO_TOTAL_PTD decimal(8,2) NOT NULL,
	ID_QUAD int(11) NOT NULL,
    ID_CRIADOR INT NOT NULL,
    
    FOREIGN KEY (ID_QUAD) REFERENCES QUADRAS (ID_QUAD),
    FOREIGN KEY (ID_CRIADOR) REFERENCES JOGADORES (ID_JOG)
);

CREATE TABLE JOGADOR_PARTIDA (
	ID_JOG_PTD int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_JOG int(11) NOT NULL,
	ID_PTD int(11) NOT NULL,
    
    FOREIGN KEY (ID_JOG) REFERENCES JOGADORES (ID_JOG),
    FOREIGN KEY (ID_PTD) REFERENCES PARTIDAS (ID_PTD)
);


INSERT INTO MODALIDADES (ID_MODAL, NOME_MODAL, QTD_MAX_JOG) VALUES
(1, 'CAMPO', 46),
(2, 'SOCIETY', 30),
(3, 'QUADRA', 28);

INSERT INTO UF (ID_UF, SIGLA_UF, NOME_UF) VALUES
(1, 'AC', 'Acre'),
(2, 'AL', 'Alagoas'),
(3, 'AP', 'Amapá'),
(4, 'AM', 'Amazonas'),
(5, 'BA', 'Bahia'),
(6, 'CE', 'Ceará'),
(7, 'DF', 'Distrito Federal'),
(8, 'ES', 'Espírito Santo'),
(9, 'GO', 'Goiás'),
(10, 'MA', 'Maranhão'),
(11, 'MT', 'Mato Grosso'),
(12, 'MS', 'Mato Grosso do Sul'),
(13, 'MG', 'Minas Gerais'),
(14, 'PA', 'Pará'),
(15, 'PB', 'Paraíba'),
(16, 'PR', 'Paraná'),
(17, 'PE', 'Pernambuco'),
(18, 'PI', 'Piauí'),
(19, 'RJ', 'Rio de Janeiro'),
(20, 'RN', 'Rio Grande do Norte'),
(21, 'RS', 'Rio Grande do Sul'),
(22, 'RO', 'Rondônia'),
(23, 'RR', 'Roraima'),
(24, 'SC', 'Santa Catarina'),
(25, 'SP', 'São Paulo'),
(26, 'SE', 'Sergipe'),
(27, 'TO', 'Tocantins');